version: "3.9"
services:
  app:
    build:
      context: .
    container_name: phpbfr
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: App
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
